import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer";
import Button from "./components/Button";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Katja Mähleke",
  description: "Generated by create next app",
};

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
